export interface OrderInterface {
	address:string;
	car?:Array<string>;	
	currency?:string;
	email?:string;
	clientEmail?:string;
	daysPerMonth?:number;
	hoursPerDay?:number;
	houseSize?:number;
	ncleaners?:number;
	direccion?:string;
	id?:string;
	metodo?:string;
	name?:string;
	personaContacto?:string;
	phone?:string;
	quoteId?:string;
	quoteIdPre?:number;
	status?:string;
	subject?:string;
	subjectA2U?:string;
	telefono?:string;
	serviceType?:string;
	total?:number;
	npedido?:string;
	steeps?:Array<any>;	
	pagoImage?:Array<string>;
}
